import type { Metadata } from "next";
import { inter, poppins } from "@/lib/fonts";
import { Header } from "@/components/header/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "RIFT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} ${poppins.variable} font-poppins antialiased`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
