import type { Metadata } from "next";
import { inter, poppins } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "RIFT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} ${poppins.variable} font-poppins`}>{children}</body>
    </html>
  );
}
